### ISSUE TITLE
can't build v1.1.0 under osx, licenseTest fails

### ISSUE THREAD

**Issue by chocolate-elvis** [DSRCorporation/imf-conversion#28]
Downloading the latest build, build fails with licenseTest. Is there a flag I can use to avoid this?
Thanks!

Example output:

dpp-conversion:licenseMain FAILED
dpp-conversion:licenseTest FAILED
dpp-conversion-input-xsd:licenseMain FAILED
imf-conversion-common:licenseMain FAILED
imf-conversion-common:licenseTest FAILED
imf-conversion-core:licenseMain FAILED
imf-conversion-core:licenseTest FAILED
imf-conversion-utility:licenseMain FAILED
imf-validation:licenseMain FAILED
imf-validation:licenseTest FAILED
itunes-conversion:licenseMain FAILED
itunes-conversion:licenseTest FAILED
itunes-conversion-input-xsd:licenseMain FAILED
ttml-to-stl:licenseMain FAILED
ttml-to-stl:licenseTest FAILED
ttml2itt:licenseMain FAILED
ttml2itt:licenseTest FAILED
ttml2scc:licenseMain FAILED

**Comment by kgoncharov** [comment]
Fixed on master branch.
As a workaround to avoid build failures you can set  license plugin flag **ignoreFailures = true** in  **build.gradle**
`
    apply plugin: 'com.github.hierynomus.license'
    license {
        ...
       ignoreFailures = true
    }
`

**Comment by kgoncharov** [comment]
Also, new release v1.1.1 contains this issue fix.
